/**
 * Generate module registry files by scanning a pages directory.
 *
 * Produces two files:
 *   - Client modules (async `() => import(...)` for code-splitting)
 *   - SSR modules (sync `import X from ...` for bundling)
 */
import fs from 'node:fs'
import path from 'node:path'

export interface GenerateOptions {
  /** Pages directory to scan (default: 'pages') */
  pagesDir?: string
  /** Client async modules output (default: 'src/inertia/modules.ts') */
  clientOutput?: string
  /** SSR sync modules output (default: 'ssr-modules.ts') */
  ssrOutput?: string
  /** Working directory (default: process.cwd()) */
  cwd?: string
}

function toPascalCase(str: string): string {
  return str
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

function scanPages(dir: string, basePath = ''): Record<string, string> {
  const modules: Record<string, string> = {}
  if (!fs.existsSync(dir)) return modules

  const items = fs.readdirSync(dir)
  for (const item of items) {
    const fullPath = path.join(dir, item)
    const stat = fs.statSync(fullPath)
    if (stat.isDirectory()) {
      Object.assign(modules, scanPages(fullPath, basePath ? `${basePath}/${item}` : item))
    } else if (item.endsWith('.vue')) {
      const name = item.replace('.vue', '')
      const moduleName = basePath ? `${basePath}/${name}` : name
      modules[moduleName] = fullPath
    }
  }
  return modules
}

/**
 * Scan pages directory and generate module registry files.
 * Returns the number of modules found.
 */
export function generateModules(options: GenerateOptions = {}): number {
  const cwd = options.cwd || process.cwd()
  const pagesDir = path.resolve(cwd, options.pagesDir || 'pages')
  const clientOutput = path.resolve(cwd, options.clientOutput || 'src/inertia/modules.ts')
  const ssrOutput = path.resolve(cwd, options.ssrOutput || 'ssr-modules.ts')

  const modules = scanPages(pagesDir)
  const keys = Object.keys(modules).sort()

  // === Client async modules ===
  let clientContent = `import type { Component } from 'vue';\n\n`
  clientContent += `// Auto-generated by millken-inertia-vue — do not edit manually\n`
  clientContent += `export const modules: Record<string, () => Promise<Component>> = {\n\n`

  for (const name of keys) {
    let rel = path.relative(path.dirname(clientOutput), modules[name]).replace(/\\/g, '/')
    if (!rel.startsWith('.') && !rel.startsWith('/')) rel = './' + rel
    clientContent += `  ${JSON.stringify(name)}: () => import(${JSON.stringify(rel)}),\n`
  }
  clientContent += `}\n`

  const clientDir = path.dirname(clientOutput)
  if (!fs.existsSync(clientDir)) fs.mkdirSync(clientDir, { recursive: true })
  fs.writeFileSync(clientOutput, clientContent, 'utf8')
  console.log(`Generated client modules: ${clientOutput}`)

  // === SSR sync modules ===
  const imports: string[] = []
  const entries: string[] = []
  const usedIds = new Map<string, number>()

  for (const name of keys) {
    const idBase = toPascalCase(name)
    let id = idBase || 'Page'
    if (/^[0-9]/.test(id)) id = '_' + id
    if (usedIds.has(id)) {
      const count = usedIds.get(id)! + 1
      usedIds.set(id, count)
      id = id + count
    } else {
      usedIds.set(id, 0)
    }

    let rel = path.relative(path.dirname(ssrOutput), modules[name]).replace(/\\/g, '/')
    if (!rel.startsWith('.') && !rel.startsWith('/')) rel = './' + rel

    imports.push(`import ${id} from ${JSON.stringify(rel)}`)
    entries.push(`  ${JSON.stringify(name)}: ${id},`)
  }

  let ssrContent = `import { Component } from 'vue'\n\n`
  if (imports.length > 0) ssrContent += imports.join('\n') + '\n\n'
  ssrContent += `const modules: Record<string, Component> = {\n${entries.join('\n')}\n}\n\nexport default modules\n`

  fs.writeFileSync(ssrOutput, ssrContent, 'utf8')
  console.log(`Generated SSR modules: ${ssrOutput}`)
  console.log(`Found ${keys.length} page modules`)

  return keys.length
}
